name: Playwright Tests
on:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: "URL to run tests against"
        required: true
        default: https://my-site.com
      commit_sha:
        description: "SHA from source repo"
        required: true
      source_repo:
        description: "Source repository name"
        required: true
      source_owner:
        description: "Source repository owner"
        required: true
  repository_dispatch:
    types: ["run-my-tests", "run-my-tests-2"]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Force a non-shallow checkout, so that we can reference $GITHUB_BASE_REF.
          # See https://github.com/actions/checkout for more details.
          fetch-depth: 0
      - name: Fetch base branch
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Debug branches
        run: git branch -a
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run CHANGED Playwright tests
        if: github.event_name == 'pull_request'
        run: npx playwright test --only-changed=${{ github.base_ref }}
      - name: Run Playwright tests
        id: playwright
        run: npx playwright test
        continue-on-error: true
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
