name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: "URL to run tests against"
        required: true
        default: https://my-site.com
  repository_dispatch:
    types: ["run-my-tests", "run-my-tests-2"]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Starting test automation
        run: |
          echo "Environment: $ENVIRONMENT"
          echo "The github event is: ${{ github.event_name }}"
          echo "Run Test Here"
          echo "Below steps in action provide what you have access to use in your scripts as needed"
      - uses: actions/checkout@v5
        with:
          # Force a non-shallow checkout, so that we can reference $GITHUB_BASE_REF.
          # See https://github.com/actions/checkout for more details.
          fetch-depth: 0
      - name: Fetch base branch
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Debug branches
        run: git branch -a
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # - name: Run CHANGED Playwright tests
      #   if: github.event_name == 'pull_request'
      #   run: npx playwright test --only-changed=${{ github.base_ref }}
      - name: Run Playwright tests
        id: playwright
        run: npx playwright test
        continue-on-error: true
      # - name: Dump GitHub context
      #   id: github_context_step
      #   # The below prints out all info you have available to use in any reporting or test running from the other repo
      #   run: echo '${{ toJSON(github) }}'
      - uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Update Source Repo Check
        uses: peter-evans/create-or-update-check@v4
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          owner: ${{ github.event.client_payload.owner }}
          repo: ${{ github.event.client_payload.repo }}
          head-sha: ${{ github.event.client_payload.sha }}
          check-name: "playwright-tests"
          conclusion: ${{ steps.playwright.outcome }}
          output-title: "Playwright Test Results"
          output-summary: "✅ Playwright tests finished. Check automation repo for detailed report."
          actions: |
            [
              {
                "label": "View Report",
                "description": "Open Playwright report in automation repo",
                "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            ]
