name: Playwright Tests
on:
  # push:
  #   branches: [main, master]
  # pull_request:
  #   branches: [main, master, develop]
  workflow_dispatch:
    inputs:
      environment:
        description: "URL to run tests against"
        required: true
        default: https://my-site.com
      commit_sha:
        description: "SHA from source repo"
        required: true
      source_repo:
        description: "Source repository name"
        required: true
      source_owner:
        description: "Source repository owner"
        required: true
  repository_dispatch:
    types: ["run-my-tests", "run-my-tests-2"]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV variables from workflow inputs
        run: |
          echo "ENVIRONMENT=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.event.inputs.commit_sha }}" >> $GITHUB_ENV
          echo "SOURCE_REPO=${{ github.event.inputs.source_repo }}" >> $GITHUB_ENV
          echo "SOURCE_OWNER=${{ github.event.inputs.source_owner }}" >> $GITHUB_ENV
      - uses: actions/checkout@v5
        with:
          # Force a non-shallow checkout, so that we can reference $GITHUB_BASE_REF.
          # See https://github.com/actions/checkout for more details.
          fetch-depth: 0
      # - name: Fetch base branch
      #   if: github.event_name == 'pull_request'
      #   run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
      # - name: Debug branches
      #   run: git branch -a
      # - uses: actions/setup-node@v5
      #   with:
      #     node-version: lts/*
      #     cache: npm
      # - name: Install dependencies
      #   run: npm ci
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run CHANGED Playwright tests
      #   if: github.event_name == 'pull_request'
      #   run: npx playwright test --only-changed=${{ github.base_ref }}
      # - name: Run Playwright tests
      #   id: playwright
      #   run: npx playwright test
      #   continue-on-error: true
      # - name: Dump GitHub context
      #   id: github_context_step
      #   # The below prints out all info you have available to use in any reporting or test running from the other repo
      #   run: echo '${{ toJSON(github) }}'
      # - uses: actions/upload-artifact@v6
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
      - name: Set Test Outcome
        run: |
          echo "FAILED" > outcome.txt
        continue-on-error: true
      - name: Set Test Outcome ENV
        run: |
          if [ -f outcome.txt ]; then
            echo "TEST_OUTCOME=failure" >> $GITHUB_ENV
          else
            echo "TEST_OUTCOME=success" >> $GITHUB_ENV
          fi
      - name: Update Source Repo Status
        if: ${{ always() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          script: |
            const owner = "";
            const repo = process.env.SOURCE_REPO;
            const sha = process.env.COMMIT_SHA;
            const state = process.env.TEST_OUTCOME; // ✅ use env variable

            console.log(`Updating ${owner}/${repo}@${sha} status to ${state}`);

            await github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state,
              context: "playwright-tests",
              description: "Playwright automation result",
              target_url: `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`
            });
      - name: Fail if Playwright tests failed
        if: ${{ steps.playwright.outcome != 'success' }}
        run: exit 1
